name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Obtener configuración de Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.ORGID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}

      - name: Instalar dependencias
        run: npm ci

      - name: Build del proyecto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.ORGID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}

      - name: Deploy a producción
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.ORGID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
